import type { Metadata } from "next";
import "./globals.css";
import 'bootstrap-icons/font/bootstrap-icons.css'
import "bootstrap/dist/css/bootstrap.min.css";
import { Roboto } from 'next/font/google'
import InstallBootstrap from "@/components/InstallBootstrap";
import StyledComponentsRegistry from '../lib/registry'
import Script from "next/script";


 
const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: "The Best Web Development Agency",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {



  return (
    <html lang="en">
      <head>
      <Script
        strategy="lazyOnload"
        src={`https://www.googletagmanager.com/gtag/js?id=${process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS}`}
      />

      <Script id="easyweb" strategy="lazyOnload">
        {`
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());
          gtag('config', '${process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS}',{
          page_path: window.location.pathname,
        });
         `}
      </Script>
      </head>
      <InstallBootstrap/>
      <body className={roboto.className}>
      <StyledComponentsRegistry>

    {children}
    </StyledComponentsRegistry>

</body>
    </html>
  );
}
